### PR TITLE
Remove unused code and files

### PR DESCRIPTION
**Pull request by da-kami**

### CODE REVIEW

**Comment by da-kami** [comment]
@yosriady is there a problem with CI?
Looks like the installs are failing. 

image

**Comment by yosriady** [comment]
@da-kami Yeah, looks like it. Odd, because the last commit only had lint errors https://github.com/comit-network/taker-ui/runs/844127189

I think it might be the ubuntu pipeline? The other pipelines are halted if another has an error. What you're seeing is the `macos-latest` pipeline being cancelled early because of a failure in `ubuntu-latest`: https://github.com/comit-network/taker-ui/runs/864205265?check_suite_focus=true

Screenshot 2020-07-13 at 1 35 59 PM

Looks like a Github availability issue to me.

**Comment by yosriady** [comment]
@da-kami Could you retrigger the pipeline to check if it's a transient fault? Just make another push.

**Review by yosriady — APPROVED** [review]

**Comment by da-kami** [comment]
Puh, after re-trigger I noticed there is quite a lot of `yarn tsc` errors. Started cleaning up, but decided it might actually be better to wire in the Bitcoin wallet first, otherwise I have to touch some things twice.

Not sure if this PR should get merged. What do you think @yosriady ?

**Comment by yosriady** [comment]
@da-kami You don't have to fix all the lint errors, just fix the ones you can and I'll fix the rest.

**Comment by da-kami** [comment]
Closing this in favour of doing doing it together with the Bitcoin wallet PR.

**Pull request closed without merging**
